# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateTimeField(verbose_name='Data do Evento')),
            ],
        ),
    ]
